# Generated by Django 4.1.7 on 2023-03-30 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user", name="username", field=models.CharField(max_length=200),
        ),
    ]
