# Generated by Django 4.2 on 2023-04-29 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_item_color_item_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='color',
            field=models.CharField(blank=True, default='null', max_length=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.CharField(blank=True, default='null', max_length=800),
        ),
    ]
