# Generated by Django 4.1.7 on 2023-05-01 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0006_alter_item_color_alter_item_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="position",
            field=models.IntegerField(default=None, null=True),
        ),
    ]
