# Generated by Django 4.1.7 on 2023-05-03 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0008_alter_item_position"),
    ]

    operations = [
        migrations.AddField(
            model_name="board",
            name="position",
            field=models.IntegerField(default=0, null=True),
        ),
    ]
